FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["aviansync.csproj", "./"]
RUN dotnet restore "aviansync.csproj"
COPY . ./
RUN dotnet publish "aviansync.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine
WORKDIR /app
EXPOSE 8080
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "aviansync.dll"]
